# Generated by Django 5.1.1 on 2024-12-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shope',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shope',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='shope',
            name='description',
        ),
    ]
