# Generated by Django 5.1.1 on 2024-12-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_initial'),
        ('sunil', '0002_remove_shope_address_remove_shope_contact_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
