# Generated by Django 5.1.1 on 2024-12-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0023_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_invoice_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
