# Generated by Django 5.1.1 on 2024-12-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_purchase_purchase_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
